var rngCopy = [];
var rngCopy2 = [];
var RNG = [];
var end = 0;
while(RNG.length < 16){
    debugger
    var r = Math.ceil(Math.random() * 16);
    var n = r;
    var z = n;
    if(RNG.indexOf(r) === -1) RNG.push(r);
    if(rngCopy.indexOf(n) === -1) rngCopy.push(n);
    if(rngCopy2.indexOf(z) === -1) rngCopy2.push(z);
}
console.log(RNG);
setTimeout(myFunction, 1000);
function myFunction(){
    end++;
    if(end > 16){
        step1();
    }
    document.getElementById(RNG.pop()).classList.add(`black`);
    setTimeout(myFunction, 500);
}
a = rngCopy.pop();
b = rngCopy2.pop();
c = rngCopy2.pop();
d = rngCopy.pop();
e = rngCopy.pop();
f = rngCopy2.pop();
g = rngCopy2.pop();
h = rngCopy.pop();
i = rngCopy.pop();
j = rngCopy2.pop();
k = rngCopy2.pop();
l = rngCopy.pop();
m = rngCopy.pop();
n = rngCopy2.pop();
o = rngCopy2.pop();
p = rngCopy.pop();
q = rngCopy.pop();
r = rngCopy2.pop();
s = rngCopy2.pop();
t = rngCopy.pop();
u = rngCopy.pop();
v = rngCopy2.pop();
w = rngCopy2.pop();
x = rngCopy.pop();
y = rngCopy.pop();
z = rngCopy2.pop();
ა = rngCopy2.pop();
ბ = rngCopy.pop();
გ = rngCopy.pop();
დ = rngCopy2.pop();
ე = rngCopy2.pop();
ვ = rngCopy.pop();
function step1(){
    alert(`your turn`);
    document.getElementById(d).addEventListener('click', fail)
    document.getElementById(e).addEventListener('click', fail)
    document.getElementById(h).addEventListener('click', fail)
    document.getElementById(i).addEventListener('click', fail)
    document.getElementById(l).addEventListener('click', fail)
    document.getElementById(m).addEventListener('click', fail)
    document.getElementById(p).addEventListener('click', fail)
    document.getElementById(q).addEventListener('click', fail)
    document.getElementById(t).addEventListener('click', fail)
    document.getElementById(u).addEventListener('click', fail)
    document.getElementById(x).addEventListener('click', fail)
    document.getElementById(y).addEventListener('click', fail)
    document.getElementById(ბ).addEventListener('click', fail)
    document.getElementById(გ).addEventListener('click', fail)
    document.getElementById(ვ).addEventListener('click', fail)
    document.getElementById(a).addEventListener('click', step2)
}function step2(){
    REL1();
    debugger
    document.getElementById(b).classList.remove('black')
    document.getElementById(b).addEventListener('click', fail)
    document.getElementById(f).addEventListener('click', fail)
    document.getElementById(g).addEventListener('click', fail)
    document.getElementById(j).addEventListener('click', fail)
    document.getElementById(k).addEventListener('click', fail)
    document.getElementById(n).addEventListener('click', fail)
    document.getElementById(o).addEventListener('click', fail)
    document.getElementById(r).addEventListener('click', fail)
    document.getElementById(s).addEventListener('click', fail)
    document.getElementById(v).addEventListener('click', fail)
    document.getElementById(w).addEventListener('click', fail)
    document.getElementById(z).addEventListener('click', fail)
    document.getElementById(ა).addEventListener('click', fail)
    document.getElementById(დ).addEventListener('click', fail)
    document.getElementById(ე).addEventListener('click', fail)
    document.getElementById(c).addEventListener('click', step3)
}function step3(){
    REL2()
    document.getElementById(d).classList.remove('black')
    document.getElementById(a).addEventListener('click', fail)
    document.getElementById(d).addEventListener('click', fail)
    document.getElementById(h).addEventListener('click', fail)
    document.getElementById(i).addEventListener('click', fail)
    document.getElementById(l).addEventListener('click', fail)
    document.getElementById(m).addEventListener('click', fail)
    document.getElementById(p).addEventListener('click', fail)
    document.getElementById(q).addEventListener('click', fail)
    document.getElementById(t).addEventListener('click', fail)
    document.getElementById(u).addEventListener('click', fail)
    document.getElementById(x).addEventListener('click', fail)
    document.getElementById(y).addEventListener('click', fail)
    document.getElementById(ბ).addEventListener('click', fail)
    document.getElementById(გ).addEventListener('click', fail)
    document.getElementById(ვ).addEventListener('click', fail)
    document.getElementById(e).addEventListener('click', step4)
}function step4(){
    REL3();
    document.getElementById(f).classList.remove('black')
    document.getElementById(b).addEventListener('click', fail)
    document.getElementById(c).addEventListener('click', fail)
    document.getElementById(f).addEventListener('click', fail)
    document.getElementById(j).addEventListener('click', fail)
    document.getElementById(k).addEventListener('click', fail)
    document.getElementById(n).addEventListener('click', fail)
    document.getElementById(o).addEventListener('click', fail)
    document.getElementById(r).addEventListener('click', fail)
    document.getElementById(s).addEventListener('click', fail)
    document.getElementById(v).addEventListener('click', fail)
    document.getElementById(w).addEventListener('click', fail)
    document.getElementById(z).addEventListener('click', fail)
    document.getElementById(ა).addEventListener('click', fail)
    document.getElementById(დ).addEventListener('click', fail)
    document.getElementById(ე).addEventListener('click', fail)
    document.getElementById(g).addEventListener('click', step5)
}function step5(){
    REL4()
    document.getElementById(h).classList.remove('black')
    document.getElementById(a).addEventListener('click', fail)
    document.getElementById(d).addEventListener('click', fail)
    document.getElementById(e).addEventListener('click', fail)
    document.getElementById(h).addEventListener('click', fail)
    document.getElementById(l).addEventListener('click', fail)
    document.getElementById(m).addEventListener('click', fail)
    document.getElementById(p).addEventListener('click', fail)
    document.getElementById(q).addEventListener('click', fail)
    document.getElementById(t).addEventListener('click', fail)
    document.getElementById(u).addEventListener('click', fail)
    document.getElementById(x).addEventListener('click', fail)
    document.getElementById(y).addEventListener('click', fail)
    document.getElementById(ბ).addEventListener('click', fail)
    document.getElementById(გ).addEventListener('click', fail)
    document.getElementById(ვ).addEventListener('click', fail)
    document.getElementById(i).addEventListener('click', step6)
}function step6(){
    REL5()
    document.getElementById(j).classList.remove('black')
    document.getElementById(b).addEventListener('click', fail)
    document.getElementById(c).addEventListener('click', fail)
    document.getElementById(f).addEventListener('click', fail)
    document.getElementById(g).addEventListener('click', fail)
    document.getElementById(j).addEventListener('click', fail)
    document.getElementById(n).addEventListener('click', fail)
    document.getElementById(o).addEventListener('click', fail)
    document.getElementById(r).addEventListener('click', fail)
    document.getElementById(s).addEventListener('click', fail)
    document.getElementById(v).addEventListener('click', fail)
    document.getElementById(w).addEventListener('click', fail)
    document.getElementById(z).addEventListener('click', fail)
    document.getElementById(ა).addEventListener('click', fail)
    document.getElementById(დ).addEventListener('click', fail)
    document.getElementById(ე).addEventListener('click', fail)
    document.getElementById(k).addEventListener('click', step7)
}function step7(){
    REL6()
    document.getElementById(l).classList.remove('black')
    document.getElementById(a).addEventListener('click', fail)
    document.getElementById(d).addEventListener('click', fail)
    document.getElementById(e).addEventListener('click', fail)
    document.getElementById(h).addEventListener('click', fail)
    document.getElementById(i).addEventListener('click', fail)
    document.getElementById(l).addEventListener('click', fail)
    document.getElementById(p).addEventListener('click', fail)
    document.getElementById(q).addEventListener('click', fail)
    document.getElementById(t).addEventListener('click', fail)
    document.getElementById(u).addEventListener('click', fail)
    document.getElementById(x).addEventListener('click', fail)
    document.getElementById(y).addEventListener('click', fail)
    document.getElementById(ბ).addEventListener('click', fail)
    document.getElementById(გ).addEventListener('click', fail)
    document.getElementById(ვ).addEventListener('click', fail)
    document.getElementById(m).addEventListener('click', step8)
}function step8(){
    REL7()
    document.getElementById(n).classList.remove('black')
    document.getElementById(b).addEventListener('click', fail)
    document.getElementById(c).addEventListener('click', fail)
    document.getElementById(f).addEventListener('click', fail)
    document.getElementById(g).addEventListener('click', fail)
    document.getElementById(j).addEventListener('click', fail)
    document.getElementById(k).addEventListener('click', fail)
    document.getElementById(n).addEventListener('click', fail)
    document.getElementById(r).addEventListener('click', fail)
    document.getElementById(s).addEventListener('click', fail)
    document.getElementById(v).addEventListener('click', fail)
    document.getElementById(w).addEventListener('click', fail)
    document.getElementById(z).addEventListener('click', fail)
    document.getElementById(ა).addEventListener('click', fail)
    document.getElementById(დ).addEventListener('click', fail)
    document.getElementById(ე).addEventListener('click', fail)
    document.getElementById(o).addEventListener('click', step9)
}function step9(){
    REL8()
    document.getElementById(p).classList.remove('black')
    document.getElementById(a).addEventListener('click', fail)
    document.getElementById(d).addEventListener('click', fail)
    document.getElementById(e).addEventListener('click', fail)
    document.getElementById(h).addEventListener('click', fail)
    document.getElementById(i).addEventListener('click', fail)
    document.getElementById(l).addEventListener('click', fail)
    document.getElementById(m).addEventListener('click', fail)
    document.getElementById(p).addEventListener('click', fail)
    document.getElementById(t).addEventListener('click', fail)
    document.getElementById(u).addEventListener('click', fail)
    document.getElementById(x).addEventListener('click', fail)
    document.getElementById(y).addEventListener('click', fail)
    document.getElementById(ბ).addEventListener('click', fail)
    document.getElementById(გ).addEventListener('click', fail)
    document.getElementById(ვ).addEventListener('click', fail)
    document.getElementById(q).addEventListener('click', step10)
}function step10(){
    REL9()
    document.getElementById(r).classList.remove('black')
    document.getElementById(b).addEventListener('click', fail)
    document.getElementById(c).addEventListener('click', fail)
    document.getElementById(f).addEventListener('click', fail)
    document.getElementById(g).addEventListener('click', fail)
    document.getElementById(j).addEventListener('click', fail)
    document.getElementById(k).addEventListener('click', fail)
    document.getElementById(n).addEventListener('click', fail)
    document.getElementById(o).addEventListener('click', fail)
    document.getElementById(r).addEventListener('click', fail)
    document.getElementById(v).addEventListener('click', fail)
    document.getElementById(w).addEventListener('click', fail)
    document.getElementById(z).addEventListener('click', fail)
    document.getElementById(ა).addEventListener('click', fail)
    document.getElementById(დ).addEventListener('click', fail)
    document.getElementById(ე).addEventListener('click', fail)
    document.getElementById(s).addEventListener('click', step11)
}function step11(){
    REL10()
    document.getElementById(t).classList.remove('black')
    document.getElementById(a).addEventListener('click', fail)
    document.getElementById(d).addEventListener('click', fail)
    document.getElementById(e).addEventListener('click', fail)
    document.getElementById(h).addEventListener('click', fail)
    document.getElementById(i).addEventListener('click', fail)
    document.getElementById(l).addEventListener('click', fail)
    document.getElementById(m).addEventListener('click', fail)
    document.getElementById(p).addEventListener('click', fail)
    document.getElementById(q).addEventListener('click', fail)
    document.getElementById(t).addEventListener('click', fail)
    document.getElementById(x).addEventListener('click', fail)
    document.getElementById(y).addEventListener('click', fail)
    document.getElementById(ბ).addEventListener('click', fail)
    document.getElementById(გ).addEventListener('click', fail)
    document.getElementById(ვ).addEventListener('click', fail)
    document.getElementById(u).addEventListener('click', step12)
}function step12(){
    REL11()
    document.getElementById(v).classList.remove('black')
    document.getElementById(b).addEventListener('click', fail)
    document.getElementById(c).addEventListener('click', fail)
    document.getElementById(f).addEventListener('click', fail)
    document.getElementById(g).addEventListener('click', fail)
    document.getElementById(j).addEventListener('click', fail)
    document.getElementById(k).addEventListener('click', fail)
    document.getElementById(n).addEventListener('click', fail)
    document.getElementById(o).addEventListener('click', fail)
    document.getElementById(r).addEventListener('click', fail)
    document.getElementById(s).addEventListener('click', fail)
    document.getElementById(v).addEventListener('click', fail)
    document.getElementById(z).addEventListener('click', fail)
    document.getElementById(ა).addEventListener('click', fail)
    document.getElementById(დ).addEventListener('click', fail)
    document.getElementById(ე).addEventListener('click', fail)
    document.getElementById(w).addEventListener('click', step13)
}function step13(){
    REL12()
    document.getElementById(x).classList.remove('black')
    document.getElementById(a).addEventListener('click', fail)
    document.getElementById(d).addEventListener('click', fail)
    document.getElementById(e).addEventListener('click', fail)
    document.getElementById(h).addEventListener('click', fail)
    document.getElementById(i).addEventListener('click', fail)
    document.getElementById(l).addEventListener('click', fail)
    document.getElementById(m).addEventListener('click', fail)
    document.getElementById(p).addEventListener('click', fail)
    document.getElementById(q).addEventListener('click', fail)
    document.getElementById(t).addEventListener('click', fail)
    document.getElementById(u).addEventListener('click', fail)
    document.getElementById(x).addEventListener('click', fail)
    document.getElementById(ბ).addEventListener('click', fail)
    document.getElementById(გ).addEventListener('click', fail)
    document.getElementById(ვ).addEventListener('click', fail)
    document.getElementById(y).addEventListener('click', step14)
}function step14(){
    REL13()
    document.getElementById(z).classList.remove('black')
    document.getElementById(b).addEventListener('click', fail)
    document.getElementById(c).addEventListener('click', fail)
    document.getElementById(f).addEventListener('click', fail)
    document.getElementById(g).addEventListener('click', fail)
    document.getElementById(j).addEventListener('click', fail)
    document.getElementById(k).addEventListener('click', fail)
    document.getElementById(n).addEventListener('click', fail)
    document.getElementById(o).addEventListener('click', fail)
    document.getElementById(r).addEventListener('click', fail)
    document.getElementById(s).addEventListener('click', fail)
    document.getElementById(v).addEventListener('click', fail)
    document.getElementById(w).addEventListener('click', fail)
    document.getElementById(z).addEventListener('click', fail)
    document.getElementById(დ).addEventListener('click', fail)
    document.getElementById(ე).addEventListener('click', fail)
    document.getElementById(ა).addEventListener('click', step15)
}function step15(){
    REL14()
    document.getElementById(ბ).classList.remove('black')
    document.getElementById(a).addEventListener('click', fail)
    document.getElementById(d).addEventListener('click', fail)
    document.getElementById(e).addEventListener('click', fail)
    document.getElementById(h).addEventListener('click', fail)
    document.getElementById(i).addEventListener('click', fail)
    document.getElementById(l).addEventListener('click', fail)
    document.getElementById(m).addEventListener('click', fail)
    document.getElementById(p).addEventListener('click', fail)
    document.getElementById(q).addEventListener('click', fail)
    document.getElementById(t).addEventListener('click', fail)
    document.getElementById(u).addEventListener('click', fail)
    document.getElementById(x).addEventListener('click', fail)
    document.getElementById(y).addEventListener('click', fail)
    document.getElementById(ბ).addEventListener('click', fail)
    document.getElementById(ვ).addEventListener('click', fail)
    document.getElementById(გ).addEventListener('click', step16)
}function step16(){
    REL15()
    document.getElementById(დ).classList.remove('black')
    document.getElementById(b).addEventListener('click', fail)
    document.getElementById(c).addEventListener('click', fail)
    document.getElementById(f).addEventListener('click', fail)
    document.getElementById(g).addEventListener('click', fail)
    document.getElementById(j).addEventListener('click', fail)
    document.getElementById(k).addEventListener('click', fail)
    document.getElementById(n).addEventListener('click', fail)
    document.getElementById(o).addEventListener('click', fail)
    document.getElementById(r).addEventListener('click', fail)
    document.getElementById(s).addEventListener('click', fail)
    document.getElementById(v).addEventListener('click', fail)
    document.getElementById(w).addEventListener('click', fail)
    document.getElementById(z).addEventListener('click', fail)
    document.getElementById(ა).addEventListener('click', fail)
    document.getElementById(დ).addEventListener('click', fail)
    document.getElementById(ე).addEventListener('click', step17)
}function step17(){
    document.getElementById(v).classList.remove(black)
    setTimeout(Win, 1000)
}function REL1(){
    document.getElementById(d).removeEventListener('click', fail)
    document.getElementById(e).removeEventListener('click', fail)
    document.getElementById(h).removeEventListener('click', fail)
    document.getElementById(i).removeEventListener('click', fail)
    document.getElementById(l).removeEventListener('click', fail)
    document.getElementById(m).removeEventListener('click', fail)
    document.getElementById(p).removeEventListener('click', fail)
    document.getElementById(q).removeEventListener('click', fail)
    document.getElementById(t).removeEventListener('click', fail)
    document.getElementById(u).removeEventListener('click', fail)
    document.getElementById(x).removeEventListener('click', fail)
    document.getElementById(y).removeEventListener('click', fail)
    document.getElementById(ბ).removeEventListener('click', fail)
    document.getElementById(გ).removeEventListener('click', fail)
    document.getElementById(ვ).removeEventListener('click', fail)
    document.getElementById(a).removeEventListener('click', step2)
}function REL2(){
    document.getElementById(b).removeEventListener('click', fail)
    document.getElementById(f).removeEventListener('click', fail)
    document.getElementById(g).removeEventListener('click', fail)
    document.getElementById(j).removeEventListener('click', fail)
    document.getElementById(k).removeEventListener('click', fail)
    document.getElementById(n).removeEventListener('click', fail)
    document.getElementById(o).removeEventListener('click', fail)
    document.getElementById(r).removeEventListener('click', fail)
    document.getElementById(s).removeEventListener('click', fail)
    document.getElementById(v).removeEventListener('click', fail)
    document.getElementById(w).removeEventListener('click', fail)
    document.getElementById(z).removeEventListener('click', fail)
    document.getElementById(ა).removeEventListener('click', fail)
    document.getElementById(დ).removeEventListener('click', fail)
    document.getElementById(ე).removeEventListener('click', fail)
    document.getElementById(c).removeEventListener('click', step3)
}function REL3(){
    document.getElementById(a).removeEventListener('click', fail)
    document.getElementById(d).removeEventListener('click', fail)
    document.getElementById(h).removeEventListener('click', fail)
    document.getElementById(i).removeEventListener('click', fail)
    document.getElementById(l).removeEventListener('click', fail)
    document.getElementById(m).removeEventListener('click', fail)
    document.getElementById(p).removeEventListener('click', fail)
    document.getElementById(q).removeEventListener('click', fail)
    document.getElementById(t).removeEventListener('click', fail)
    document.getElementById(u).removeEventListener('click', fail)
    document.getElementById(x).removeEventListener('click', fail)
    document.getElementById(y).removeEventListener('click', fail)
    document.getElementById(ბ).removeEventListener('click', fail)
    document.getElementById(გ).removeEventListener('click', fail)
    document.getElementById(ვ).removeEventListener('click', fail)
    document.getElementById(e).removeEventListener('click', step4)
}function REL4(){
    document.getElementById(b).removeEventListener('click', fail)
    document.getElementById(c).removeEventListener('click', fail)
    document.getElementById(f).removeEventListener('click', fail)
    document.getElementById(j).removeEventListener('click', fail)
    document.getElementById(k).removeEventListener('click', fail)
    document.getElementById(n).removeEventListener('click', fail)
    document.getElementById(o).removeEventListener('click', fail)
    document.getElementById(r).removeEventListener('click', fail)
    document.getElementById(s).removeEventListener('click', fail)
    document.getElementById(v).removeEventListener('click', fail)
    document.getElementById(w).removeEventListener('click', fail)
    document.getElementById(z).removeEventListener('click', fail)
    document.getElementById(ა).removeEventListener('click', fail)
    document.getElementById(დ).removeEventListener('click', fail)
    document.getElementById(ე).removeEventListener('click', fail)
    document.getElementById(g).removeEventListener('click', step5)
}function REL5(){
    document.getElementById(a).removeEventListener('click', fail)
    document.getElementById(d).removeEventListener('click', fail)
    document.getElementById(e).removeEventListener('click', fail)
    document.getElementById(h).removeEventListener('click', fail)
    document.getElementById(l).removeEventListener('click', fail)
    document.getElementById(m).removeEventListener('click', fail)
    document.getElementById(p).removeEventListener('click', fail)
    document.getElementById(q).removeEventListener('click', fail)
    document.getElementById(t).removeEventListener('click', fail)
    document.getElementById(u).removeEventListener('click', fail)
    document.getElementById(x).removeEventListener('click', fail)
    document.getElementById(y).removeEventListener('click', fail)
    document.getElementById(ბ).removeEventListener('click', fail)
    document.getElementById(გ).removeEventListener('click', fail)
    document.getElementById(ვ).removeEventListener('click', fail)
    document.getElementById(i).removeEventListener('click', step6)
}function REL6(){
    document.getElementById(b).removeEventListener('click', fail)
    document.getElementById(c).removeEventListener('click', fail)
    document.getElementById(f).removeEventListener('click', fail)
    document.getElementById(g).removeEventListener('click', fail)
    document.getElementById(j).removeEventListener('click', fail)
    document.getElementById(n).removeEventListener('click', fail)
    document.getElementById(o).removeEventListener('click', fail)
    document.getElementById(r).removeEventListener('click', fail)
    document.getElementById(s).removeEventListener('click', fail)
    document.getElementById(v).removeEventListener('click', fail)
    document.getElementById(w).removeEventListener('click', fail)
    document.getElementById(z).removeEventListener('click', fail)
    document.getElementById(ა).removeEventListener('click', fail)
    document.getElementById(დ).removeEventListener('click', fail)
    document.getElementById(ე).removeEventListener('click', fail)
    document.getElementById(k).removeEventListener('click', step7)
}function REL7(){
    document.getElementById(a).removeEventListener('click', fail)
    document.getElementById(d).removeEventListener('click', fail)
    document.getElementById(e).removeEventListener('click', fail)
    document.getElementById(h).removeEventListener('click', fail)
    document.getElementById(i).removeEventListener('click', fail)
    document.getElementById(l).removeEventListener('click', fail)
    document.getElementById(p).removeEventListener('click', fail)
    document.getElementById(q).removeEventListener('click', fail)
    document.getElementById(t).removeEventListener('click', fail)
    document.getElementById(u).removeEventListener('click', fail)
    document.getElementById(x).removeEventListener('click', fail)
    document.getElementById(y).removeEventListener('click', fail)
    document.getElementById(ბ).removeEventListener('click', fail)
    document.getElementById(გ).removeEventListener('click', fail)
    document.getElementById(ვ).removeEventListener('click', fail)
    document.getElementById(m).removeEventListener('click', step8)
}function REL8(){
    document.getElementById(b).removeEventListener('click', fail)
    document.getElementById(c).removeEventListener('click', fail)
    document.getElementById(f).removeEventListener('click', fail)
    document.getElementById(g).removeEventListener('click', fail)
    document.getElementById(j).removeEventListener('click', fail)
    document.getElementById(k).removeEventListener('click', fail)
    document.getElementById(n).removeEventListener('click', fail)
    document.getElementById(r).removeEventListener('click', fail)
    document.getElementById(s).removeEventListener('click', fail)
    document.getElementById(v).removeEventListener('click', fail)
    document.getElementById(w).removeEventListener('click', fail)
    document.getElementById(z).removeEventListener('click', fail)
    document.getElementById(ა).removeEventListener('click', fail)
    document.getElementById(დ).removeEventListener('click', fail)
    document.getElementById(ე).removeEventListener('click', fail)
    document.getElementById(o).removeEventListener('click', step9)
}function REL9(){
    document.getElementById(a).removeEventListener('click', fail)
    document.getElementById(d).removeEventListener('click', fail)
    document.getElementById(e).removeEventListener('click', fail)
    document.getElementById(h).removeEventListener('click', fail)
    document.getElementById(i).removeEventListener('click', fail)
    document.getElementById(l).removeEventListener('click', fail)
    document.getElementById(m).removeEventListener('click', fail)
    document.getElementById(p).removeEventListener('click', fail)
    document.getElementById(t).removeEventListener('click', fail)
    document.getElementById(u).removeEventListener('click', fail)
    document.getElementById(x).removeEventListener('click', fail)
    document.getElementById(y).removeEventListener('click', fail)
    document.getElementById(ბ).removeEventListener('click', fail)
    document.getElementById(გ).removeEventListener('click', fail)
    document.getElementById(ვ).removeEventListener('click', fail)
    document.getElementById(q).removeEventListener('click', step10)
}function REL10(){
    document.getElementById(b).removeEventListener('click', fail)
    document.getElementById(c).removeEventListener('click', fail)
    document.getElementById(f).removeEventListener('click', fail)
    document.getElementById(g).removeEventListener('click', fail)
    document.getElementById(j).removeEventListener('click', fail)
    document.getElementById(k).removeEventListener('click', fail)
    document.getElementById(n).removeEventListener('click', fail)
    document.getElementById(o).removeEventListener('click', fail)
    document.getElementById(r).removeEventListener('click', fail)
    document.getElementById(v).removeEventListener('click', fail)
    document.getElementById(w).removeEventListener('click', fail)
    document.getElementById(z).removeEventListener('click', fail)
    document.getElementById(ა).removeEventListener('click', fail)
    document.getElementById(დ).removeEventListener('click', fail)
    document.getElementById(ე).removeEventListener('click', fail)
    document.getElementById(s).removeEventListener('click', step11)
}function REL11(){
    document.getElementById(a).removeEventListener('click', fail)
    document.getElementById(d).removeEventListener('click', fail)
    document.getElementById(e).removeEventListener('click', fail)
    document.getElementById(h).removeEventListener('click', fail)
    document.getElementById(i).removeEventListener('click', fail)
    document.getElementById(l).removeEventListener('click', fail)
    document.getElementById(m).removeEventListener('click', fail)
    document.getElementById(p).removeEventListener('click', fail)
    document.getElementById(q).removeEventListener('click', fail)
    document.getElementById(t).removeEventListener('click', fail)
    document.getElementById(x).removeEventListener('click', fail)
    document.getElementById(y).removeEventListener('click', fail)
    document.getElementById(ბ).removeEventListener('click', fail)
    document.getElementById(გ).removeEventListener('click', fail)
    document.getElementById(ვ).removeEventListener('click', fail)
    document.getElementById(u).removeEventListener('click', step12)
}function REL12(){
    document.getElementById(b).removeEventListener('click', fail)
    document.getElementById(c).removeEventListener('click', fail)
    document.getElementById(f).removeEventListener('click', fail)
    document.getElementById(g).removeEventListener('click', fail)
    document.getElementById(j).removeEventListener('click', fail)
    document.getElementById(k).removeEventListener('click', fail)
    document.getElementById(n).removeEventListener('click', fail)
    document.getElementById(o).removeEventListener('click', fail)
    document.getElementById(r).removeEventListener('click', fail)
    document.getElementById(s).removeEventListener('click', fail)
    document.getElementById(v).removeEventListener('click', fail)
    document.getElementById(z).removeEventListener('click', fail)
    document.getElementById(ა).removeEventListener('click', fail)
    document.getElementById(დ).removeEventListener('click', fail)
    document.getElementById(ე).removeEventListener('click', fail)
    document.getElementById(w).removeEventListener('click', step13)
}function REL13(){
    document.getElementById(a).removeEventListener('click', fail)
    document.getElementById(d).removeEventListener('click', fail)
    document.getElementById(e).removeEventListener('click', fail)
    document.getElementById(h).removeEventListener('click', fail)
    document.getElementById(i).removeEventListener('click', fail)
    document.getElementById(l).removeEventListener('click', fail)
    document.getElementById(m).removeEventListener('click', fail)
    document.getElementById(p).removeEventListener('click', fail)
    document.getElementById(q).removeEventListener('click', fail)
    document.getElementById(t).removeEventListener('click', fail)
    document.getElementById(u).removeEventListener('click', fail)
    document.getElementById(x).removeEventListener('click', fail)
    document.getElementById(ბ).removeEventListener('click', fail)
    document.getElementById(გ).removeEventListener('click', fail)
    document.getElementById(ვ).removeEventListener('click', fail)
    document.getElementById(y).removeEventListener('click', step14)
}function REL14(){
    document.getElementById(b).removeEventListener('click', fail)
    document.getElementById(c).removeEventListener('click', fail)
    document.getElementById(f).removeEventListener('click', fail)
    document.getElementById(g).removeEventListener('click', fail)
    document.getElementById(j).removeEventListener('click', fail)
    document.getElementById(k).removeEventListener('click', fail)
    document.getElementById(n).removeEventListener('click', fail)
    document.getElementById(o).removeEventListener('click', fail)
    document.getElementById(r).removeEventListener('click', fail)
    document.getElementById(s).removeEventListener('click', fail)
    document.getElementById(v).removeEventListener('click', fail)
    document.getElementById(w).removeEventListener('click', fail)
    document.getElementById(z).removeEventListener('click', fail)
    document.getElementById(დ).removeEventListener('click', fail)
    document.getElementById(ე).removeEventListener('click', fail)
    document.getElementById(ა).removeEventListener('click', step15)
}function REL15(){
    document.getElementById(a).removeEventListener('click', fail)
    document.getElementById(d).removeEventListener('click', fail)
    document.getElementById(e).removeEventListener('click', fail)
    document.getElementById(h).removeEventListener('click', fail)
    document.getElementById(i).removeEventListener('click', fail)
    document.getElementById(l).removeEventListener('click', fail)
    document.getElementById(m).removeEventListener('click', fail)
    document.getElementById(p).removeEventListener('click', fail)
    document.getElementById(q).removeEventListener('click', fail)
    document.getElementById(t).removeEventListener('click', fail)
    document.getElementById(u).removeEventListener('click', fail)
    document.getElementById(x).removeEventListener('click', fail)
    document.getElementById(y).removeEventListener('click', fail)
    document.getElementById(ბ).removeEventListener('click', fail)
    document.getElementById(ვ).removeEventListener('click', fail)
    document.getElementById(გ).removeEventListener('click', step16)
}
function fail(){
    alert(`you lost`);
    location.reload()
}
function Win(){
    localStorage.setItem(`act19`, `true`);
    alert('you won')
    location.replace('.././index.html');
}
